import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import DashboardDrawer from '@/component/drawer/DashboardDrawer';
import withAuth from './protected/projected';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'portfolio dashboard',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardDrawer>{children}</DashboardDrawer>
      </body>
    </html>
  );
};

export default RootLayout;
